environment          = "dev"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.11.0/24", "10.0.12.0/24"]
azs                  = ["us-east-1a", "us-east-1b"]
instance_type        = "t3.micro"
min_size             = 1
max_size             = 2
desired_capacity     = 1
bucket_name          = "muskan-acs730-dev-images"
image_key            = "website-image.jpg"
name_prefix          = "Muskan"